### {{ ansible_managed }}
### If you make edits then need to run the ansible playbook, copy the file off and back

status = warn

name = DR2LambdaLogConfiguration

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = JsonTemplateLayout
appender.console.layout.eventTemplateUri = classpath:EcsLayout.json

appender.file.type = File
appender.file.name = FILE
appender.file.fileName = /poduser/logs/custodial-copy-webapp.log
appender.file.layout.type = JsonTemplateLayout
appender.file.layout.eventTemplateUri = classpath:EcsLayout.json

## Root Logger Configuration
rootLogger.level = debug
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = FILE

logger.io-ocfl.name = io.ocfl
logger.io-ocfl.level = info
logger.io-ocfl.appenderRef.stdout.ref = STDOUT
logger.io-ocfl.appenderRef.file.ref = FILE

logger.file-util.name = io.ocfl.core.util.FileUtil
logger.file-util.level = info
logger.file-util.appenderRef.stdout.ref = STDOUT
logger.file-util.appenderRef.file.ref = FILE

logger.preservica.name = uk.gov.nationalarchives.dp
logger.preservica.level = info
logger.preservica.appenderRef.stdout.ref = STDOUT
logger.preservica.appenderRef.file.ref = FILE

logger.sttp.name = sttp.client4.logging.slf4j.Slf4jLoggingBackend
logger.sttp.level = info
logger.sttp.appenderRef.stdout.ref = STDOUT
logger.sttp.appenderRef.file.ref = FILE

