### {{ ansible_managed }}

[Timer]
# Remove original settings of daily (midnight) update
OnCalendar=
OnUnitActiveSec=5m
RandomizedDelaySec=30
# Update immediately after reboot if an update has been missed
Persistent=true
